### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by PauloBoaventura** [webmaniabr/jQuery-CEP-Correios#4]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by PauloBoaventura** [comment]
@webmaniabr 
Funciona em Magento 1.9 ou 2.1 ?
Obrigado pela resposta tão prontamente, que deixa uma satisfação aos clientes e desenvolvedores!

**Comment by webmaniabr** [comment]
Olá Paulo, funciona em todas as plataformas de Loja Virtual. Não possuímos um módulo para Magento, mas para o funcionamento correto você precisa adicionar o arquivo **jquery.correios.min.js** dentro da tag **< head >< /head >** do seu HTML. 

Depois de adicionado o arquivo é preciso adicionar as instruções em Javascript conforme instruções: https://github.com/webmaniabr/jQuery-CEP-Correios#utiliza%C3%A7%C3%A3o

jQuery(function($){
    correios.init( 'app_key', 'app_secret' );
    $('cep').correios( 'endereco', 'bairro', 'cidade', 'uf', 'loading', true, 'numero');
});

**Comment by PauloBoaventura** [comment]
Olá @webmaniabr Obrigado pela ajuda! E parabéns pela gestão desta aplicação!
Irei testar assim que possível!

abs
